# Generated by Django 2.0.3 on 2018-03-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0002_auto_20180309_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='networks',
        ),
        migrations.AddField(
            model_name='probe_request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonde_app.Client'),
        ),
        migrations.AddField(
            model_name='probe_request',
            name='ssid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonde_app.SSID'),
        ),
    ]
