# Generated by Django 2.0.3 on 2018-03-09 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0003_auto_20180309_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe_request',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
