# Generated by Django 2.0.3 on 2018-03-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0004_probe_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
