# Generated by Django 2.0.3 on 2018-03-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='mac',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='ssid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonde_app.SSID'),
        ),
    ]
