# Generated by Django 2.0.3 on 2018-03-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0005_auto_20180309_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probe_request',
            options={'ordering': ['-timestamp']},
        ),
    ]
