# Generated by Django 2.0.3 on 2018-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0006_auto_20180321_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssid',
            name='last_wiggled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
