# Generated by Django 2.0.3 on 2018-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0007_ssid_last_wiggled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Unnamed tag', max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='probed_ssids',
            field=models.ManyToManyField(through='zonde_app.Probe_request', to='zonde_app.SSID'),
        ),
        migrations.AddField(
            model_name='ssid',
            name='probed_clients',
            field=models.ManyToManyField(through='zonde_app.Probe_request', to='zonde_app.Client'),
        ),
        migrations.AddField(
            model_name='tag',
            name='relevant_ssids',
            field=models.ManyToManyField(to='zonde_app.SSID'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(to='zonde_app.Tag'),
        ),
    ]
