# Generated by Django 2.0.3 on 2018-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonde_app', '0008_auto_20180324_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='bssid',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
